export ZSH="{{ home }}/.oh-my-zsh"
export PATH=~/.local/bin:$PATH

ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_CONTEXT_TEMPLATE=%n

plugins=(
  aws
  docker
  docker-compose
  docker-machine
  git
  kubectl
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

export TERM=xterm-256color
export EDITOR=vim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias open="xdg-open"
alias pbcopy="xclip -selection clipboard"
alias conjur="docker-compose run conjur"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'

alias gbdo="git push origin --delete"

export GOPATH="{{ home }}/go"
export PATH=$GOPATH/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
