export ZSH="{{ home }}/.oh-my-zsh"
export PATH=~/.local/bin:$PATH

ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_CONTEXT_TEMPLATE=%n

plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

export TERM=xterm-256color
export EDITOR=vim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias pbcopy="xclip -selection clipboard"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'

alias gbdo="git push origin --delete"

export GOPATH=/home/andy/go
export PATH=$GOPATH/bin:$PATH
export PATH=$PATH:/usr/local/go/bin